services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aipos
      MYSQL_USER: aipos
      MYSQL_PASSWORD: aipos
    ports:
      - "3306:3306"
